### ISSUE TITLE
Strange calibration results

### ISSUE THREAD

**Issue by parsaci** [mapircamera/QGIS#11]
Hello,
I am using the last version of Qgis MAPIR plugin (I have a MAPIR Survey2 NDVI). 
I am trying to calibrate some JPG images using default calibration coefficients.  Results are very strange, there are a lot of aritifacts so I suppose that something doesn't work. 
I attached the original file and the calibrated one.
![2015_0109_213829_010](https://cloud.githubusercontent.com/assets/28528883/25798044/ec6c75d0-33df-11e7-9608-4f961f16e83d.JPG) 
![2015_0109_213829_010_calibrated](https://cloud.githubusercontent.com/assets/28528883/25798146/4e9faa92-33e0-11e7-8037-b3919ce9b4ee.JPG)

**Comment by mapircamera** [comment]
Hello, I'll take a look into this today.

**Comment by mapircamera** [comment]
Are you calling artifacts the contrast thresholds between one area of a leaf and another? It will do that as the leaf curves since it is reflecting light differently in numerous directions.

Using the default calibration for this lighting situation won't work well due to the light source being very off angle and not next to the camera. The default values are created for solar noon, clear sunny days. In your setup here, the light source seems to be off to the top right. You would need to have the calibration target to get the values closer to their true values.

Reflectance calibration using ground targets works best when the sun is more overhead and shadows are reduced.

**Comment by parsaci** [comment]
Thank you for your quick answer. 
I understand what you are saying, at first I also thought that the problem were the shooting wrong light conditions. The problem, however, is that this strange behaviour also happens with images with better light conditions, such as those taken from the Mapir site (I attached file a 1024x1024 tile of image 2016_0501_142544_068.jpg taken from here https://www.mapir.camera/pages/vineyard-400ft-may-1-2016). 
![2016_0501_142544_068_tile](https://cloud.githubusercontent.com/assets/28528883/25841296/d5753d6a-349f-11e7-949d-67cbf8f322ce.jpg)
![2016_0501_142544_068_tile_calibrated](https://cloud.githubusercontent.com/assets/28528883/25841299/d73a2368-349f-11e7-804f-c10f80231183.jpg)
Unfortunately, at the moment, I don't have the calibration target so I can't try with it. However I belive that, even if the calibration coefficients are incorrect, it's strange that in the image appear some black areas (this is what I mean as artifact). Calibration for tiff images, even in unrealistic light conditions,  does not yield such strange images. Also the calibration with fiji (with same coefficients) works better.

**Comment by mapircamera** [comment]
Hello, The newest version of the code should solve the problem.
